import { defineSlotRecipe } from "@chakra-ui/react";

export const phoneFieldSlotRecipe = defineSlotRecipe({
  className: "phone-field",
  slots: ["root", "label", "control", "country", "countrySelect", "flag", "input", "errorText"],
  base: {
    root: { display: "block", width: "100%", minWidth: 0 },
    label: {
      display: "block",
      maxWidth: "100%",
      marginBottom: "8px",
      fontSize: "13px",
      lineHeight: "19.5px",
      color: "ds.gray.900",
      textTransform: "capitalize",
      cursor: "text",
    },
    control: {
      display: "flex",
      alignItems: "center",
      width: "100%",
      height: "36px",
      fontSize: "14px",
      lineHeight: "21px",
      backgroundColor: "ds.page",
      borderRadius: "6px",
      boxShadow: "0 0 0 1px {colors.ds.grayAlpha.400}",
      transition: "box-shadow 0.15s",
      _hover: { boxShadow: "0 0 0 1px {colors.ds.grayAlpha.500}" },
      // Outranks hover; focus keeps its own ring.
      "&[data-invalid]:not(:focus-within)": { boxShadow: "0 0 0 1px {colors.ds.error}" },
      // !important so focus beats hover while the pointer is still over the field.
      _focusWithin: {
        boxShadow:
          "0 0 0 1px {colors.ds.grayAlpha.600}, 0 0 0 4px {colors.ds.inputRing} !important",
      },
    },
    country: {
      position: "relative",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      alignSelf: "stretch",
      flexShrink: 0,
      width: "48px",
      marginRight: "5px",
      color: "ds.gray.900",
      backgroundColor: "ds.page",
      borderRadius: "6px 0 0 6px",
      boxShadow: "1px 0 0 0 {colors.ds.grayAlpha.400}",
    },
    countrySelect: {
      position: "absolute",
      inset: 0,
      zIndex: 1,
      width: "100%",
      height: "100%",
      opacity: 0,
      cursor: "pointer",
    },
    flag: {
      display: "block",
      width: "21px",
      height: "14px",
      objectFit: "cover",
      backgroundColor: "rgba(0, 0, 0, 0.1)",
      boxShadow: "0 0 0 1px {colors.ds.gray.200}",
    },
    errorText: {
      display: "block",
      marginTop: "8px",
      fontSize: "13px",
      lineHeight: "18px",
      color: "ds.error",
    },
    input: {
      flex: "1 1 0%",
      minWidth: 0,
      height: "36px",
      paddingInline: "12px",
      fontSize: "14px",
      color: "ds.foreground",
      backgroundColor: "ds.page",
      border: "none",
      outline: "none",
      borderRadius: "0 6px 6px 0",
      _placeholder: { color: "ds.gray.700" },
    },
  },
});
