import { defineSlotRecipe } from "@chakra-ui/react";

export const siteFooterRecipe = defineSlotRecipe({
  className: "vc-site-footer",
  slots: [
    "root",
    "inner",
    "grid",
    "column",
    "heading",
    "list",
    "item",
    "link",
    "badge",
    "logoLink",
    "bottom",
    "status",
    "statusDot",
    "statusText",
    "tools",
    "themeSwitch",
    "themeLegend",
    "themeInput",
    "themeOption",
    "agentButton",
  ],
  base: {
    root: {
      paddingTop: "64px",
      borderTop: "1px solid {colors.ds.footerBorder}",
      backgroundColor: "ds.page",
    },
    inner: {
      maxWidth: "{sizes.pageWithMargin}",
      marginInline: "auto",
      padding: "40px {spacing.pageMargin}",
      fontSize: "14px",
      lineHeight: "21px",
    },
    grid: {
      display: "grid",
      gap: "24px",
      gridTemplateColumns: {
        base: "repeat(4, minmax(0, 1fr))",
        sm: "repeat(6, minmax(0, 1fr))",
        lg: "repeat(8, minmax(0, 1fr))",
        xl: "repeat(12, minmax(0, 1fr))",
      },
    },
    column: { gridColumn: "span 2 / span 2" },
    heading: {
      marginBlock: "12px",
      fontSize: "14px",
      lineHeight: "20px",
      fontWeight: 500,
      color: "ds.gray.1000",
    },
    list: { listStyle: "none", margin: 0, padding: 0 },
    item: {
      listStyle: "none",
      paddingBlock: "2px",
      fontSize: "14px",
      lineHeight: "20px",
      color: "ds.gray.900",
    },
    link: {
      display: "flex",
      alignItems: "center",
      gap: "6px",
      width: "fit-content",
      padding: "2px",
      marginLeft: "-2px",
      color: "ds.gray.900",
      textDecoration: "none",
      cursor: "pointer",
      transition: "color 0.1s cubic-bezier(0.4, 0, 0.2, 1)",
      _hover: { color: "ds.gray.1000" },
      _focusVisible: { outline: "2px solid {colors.ds.focus}", outlineOffset: "4px" },
    },
    badge: {
      display: "inline-flex",
      flexShrink: 0,
      alignItems: "center",
      justifyContent: "center",
      height: "20px",
      padding: "2px 8px",
      fontSize: "11px",
      lineHeight: "20px",
      fontWeight: 500,
      letterSpacing: "0.2px",
      whiteSpace: "nowrap",
      color: "ds.gray.1000",
      backgroundColor: "ds.badge",
      borderRadius: "9999px",
    },
    logoLink: {
      display: "flex",
      alignItems: "center",
      width: "100%",
      height: "32px",
      color: "ds.gray.1000",
    },
    bottom: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      minHeight: "34px",
      marginTop: "32px",
    },
    status: {
      display: "flex",
      alignItems: "center",
      gap: "6px",
      height: "34px",
      marginLeft: "-12px",
      paddingInline: "12px",
      whiteSpace: "nowrap",
      textDecoration: "none",
      outline: "none",
      _focusVisible: { boxShadow: "focusRing" },
    },
    statusDot: {
      flexShrink: 0,
      width: "10px",
      height: "10px",
      borderRadius: "9999px",
      backgroundColor: "ds.secondary",
    },
    statusText: {
      fontFamily: "mono",
      fontSize: "12px",
      lineHeight: "20px",
      fontWeight: 500,
      textTransform: "uppercase",
      color: "ds.secondary",
    },
    tools: { display: "flex", alignItems: "center", gap: "4px", marginLeft: "auto" },
    themeSwitch: {
      display: "flex",
      width: "fit-content",
      height: "24px",
      margin: 0,
      padding: 0,
      border: 0,
      borderRadius: "9999px",
      boxShadow: "0 0 0 1px {colors.ds.grayAlpha.400}",
    },
    themeLegend: { srOnly: true },
    themeInput: { srOnly: true },
    themeOption: {
      position: "relative",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      width: "24px",
      height: "24px",
      borderRadius: "9999px",
      color: "ds.gray.700",
      cursor: "pointer",
      _hover: { color: "ds.gray.1000" },
      "input:checked + &": {
        color: "ds.gray.1000",
        boxShadow:
          "0 0 0 1px {colors.ds.gray.400}, 0 1px 2px 0 {colors.ds.grayAlpha.100}",
      },
      "input:focus-visible + &": { boxShadow: "focusRing" },
    },
    agentButton: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      width: "24px",
      height: "24px",
      marginLeft: "4px",
      color: "ds.gray.700",
      borderRadius: "4px",
      cursor: "pointer",
      outline: "none",
      _hover: { color: "ds.gray.1000" },
      _focusVisible: { color: "ds.gray.1000", boxShadow: "focusRing" },
    },
  },
});
