import { defineSlotRecipe } from "@chakra-ui/react";

const NAV_COLLAPSE = "@media (max-width: 880px)";
const SEARCH_COLLAPSE = "@media (max-width: 960px)";

export const siteHeaderRecipe = defineSlotRecipe({
  className: "vc-site-header",
  slots: [
    "root",
    "inner",
    "logo",
    "nav",
    "navTrigger",
    "navChevron",
    "navLink",
    "panel",
    "panelInner",
    "panelColumn",
    "panelLabel",
    "panelList",
    "panelLink",
    "overlay",
    "actions",
    "desktopActions",
    "search",
    "searchLabel",
    "kbd",
    "burger",
    "mobilePanel",
    "mobileInner",
    "mobileList",
    "mobileItem",
    "mobileGroups",
    "mobileGroupLabel",
    "mobileSubLink",
    "mobileActions",
  ],
  base: {
    root: {
      position: "sticky",
      top: 0,
      zIndex: "header",
      width: "100%",
      height: "{sizes.header}",
      backgroundColor: "transparent",
    },
    inner: {
      display: "flex",
      alignItems: "center",
      gap: "12px",
      width: "100%",
      height: "100%",
      maxWidth: "{sizes.pageWithMargin}",
      marginInline: "auto",
      paddingInline: "{spacing.pageMargin}",
    },
    logo: {
      display: "inline-flex",
      alignItems: "center",
      padding: "8px",
      marginLeft: "-8px",
      color: "ds.gray.1000",
      _focusVisible: { outline: "2px solid {colors.ds.focus}", outlineOffset: "4px" },
    },
    nav: {
      display: "flex",
      alignItems: "center",
      height: "100%",
      [NAV_COLLAPSE]: { display: "none" },
    },
    navTrigger: {
      display: "flex",
      alignItems: "center",
      gap: "3px",
      padding: "6px 8px 6px 12px",
      fontSize: "14px",
      lineHeight: "20px",
      color: "ds.gray.900",
      backgroundColor: "transparent",
      cursor: "pointer",
      outline: "none",
      "&[data-open]": { color: "ds.gray.1000" },
      _focusVisible: { color: "ds.gray.1000", boxShadow: "focusRing" },
    },
    navChevron: {
      display: "inline-flex",
      pointerEvents: "none",
      "[data-open] > &": { transform: "rotate(180deg)" },
    },
    navLink: {
      display: "flex",
      alignItems: "center",
      padding: "6px 12px",
      fontSize: "14px",
      lineHeight: "20px",
      color: "ds.gray.900",
      textDecoration: "none",
      outline: "none",
      _hover: { color: "ds.gray.1000" },
      _focusVisible: { color: "ds.gray.1000", boxShadow: "focusRing" },
    },
    panel: {
      position: "fixed",
      insetInline: 0,
      top: "{sizes.header}",
      zIndex: "header",
      visibility: "hidden",
      backgroundColor: "ds.background.200",
      boxShadow: "0 1px 0 0 {colors.ds.grayAlpha.300}",
      "&[data-open]": { visibility: "visible" },
      [NAV_COLLAPSE]: { display: "none" },
    },
    panelInner: {
      display: "flex",
      flexWrap: "nowrap",
      columnGap: "16px",
      width: "100%",
      maxWidth: "{sizes.pageWithMargin}",
      marginInline: "auto",
      padding: "4px {spacing.pageMargin} 24px",
    },
    panelColumn: { minWidth: "250px", flexShrink: 0 },
    panelLabel: { fontSize: "14px", lineHeight: "20px", color: "ds.gray.900" },
    panelList: {
      display: "flex",
      flexDirection: "column",
      marginTop: "5px",
      listStyle: "none",
    },
    panelLink: {
      display: "inline-flex",
      alignItems: "center",
      gap: "4px",
      width: "100%",
      fontSize: "20px",
      lineHeight: "32px",
      color: "ds.gray.1000",
      textDecoration: "none",
      outline: "none",
      "& [data-part=text]": {
        textDecorationThickness: "1px",
        textUnderlineOffset: "5px",
        textDecorationColor: "{colors.ds.gray.500}",
      },
      "&:hover [data-part=text]": { textDecorationLine: "underline" },
      "&:focus-visible > span": { boxShadow: "focusRing" },
    },
    overlay: {
      position: "fixed",
      insetInline: 0,
      bottom: 0,
      top: "{sizes.header}",
      zIndex: "headerBelow",
      pointerEvents: "none",
      backgroundColor: "ds.overlay",
      opacity: 0,
      willChange: "opacity",
      "&[data-open]": { opacity: 1 },
      [NAV_COLLAPSE]: { display: "none" },
    },
    actions: {
      display: "flex",
      flexShrink: 0,
      alignItems: "center",
      gap: "12px",
      marginLeft: "auto",
    },
    desktopActions: {
      display: "contents",
      [NAV_COLLAPSE]: { display: "none" },
    },
    search: {
      display: "flex",
      alignItems: "center",
      gap: "8px",
      width: "240px",
      height: "32px",
      padding: "0 6px 0 8px",
      fontSize: "14px",
      lineHeight: "21px",
      borderRadius: "6px",
      backgroundColor: "ds.searchBg",
      cursor: "pointer",
      outline: "none",
      _focusVisible: { boxShadow: "focusRing" },
      [SEARCH_COLLAPSE]: { display: "none" },
    },
    searchLabel: {
      flex: "1 1 0%",
      textAlign: "left",
      color: "ds.gray.700",
      overflow: "hidden",
      textOverflow: "ellipsis",
      whiteSpace: "nowrap",
    },
    kbd: {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      minWidth: "20px",
      height: "20px",
      marginLeft: "2px",
      paddingInline: "6px",
      fontFamily: "body",
      fontSize: "12px",
      lineHeight: "20.4px",
      color: "ds.gray.900",
      backgroundColor: "ds.kbd",
      borderRadius: "2px",
      boxShadow: "0 0 0 1px {colors.ds.grayAlpha.400}",
    },
    burger: {
      display: "none",
      alignItems: "center",
      justifyContent: "center",
      minWidth: "44px",
      minHeight: "44px",
      transform: "translateX(10px)",
      color: "ds.gray.1000",
      borderRadius: "4px",
      cursor: "pointer",
      outline: "none",
      _focusVisible: { boxShadow: "focusRing" },
      [NAV_COLLAPSE]: { display: "flex" },
    },
    mobilePanel: {
      display: "none",
      position: "fixed",
      inset: 0,
      top: "{sizes.header}",
      zIndex: "headerBelow",
      overflowY: "auto",
      scrollbarWidth: "none",
      backgroundColor: "ds.background.100",
      "&::-webkit-scrollbar": { display: "none" },
    },
    mobileInner: { display: "flex", flexDirection: "column", padding: "24px" },
    mobileList: { display: "flex", flexDirection: "column", marginInline: "-12px" },
    mobileItem: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      minHeight: "44px",
      paddingInline: "12px",
      fontSize: "22px",
      lineHeight: "33px",
      fontWeight: 400,
      color: "ds.gray.900",
      borderRadius: "4px",
      textDecoration: "none",
      listStyle: "none",
      cursor: "pointer",
      outline: "none",
      transition: "color 0.15s, background-color 0.15s",
      "&::-webkit-details-marker": { display: "none" },
      "& svg": { flexShrink: 0, color: "ds.gray.1000" },
      "details[open] > &": { "& svg": { transform: "rotate(180deg)" } },
      _hover: { color: "ds.gray.1000", backgroundColor: "ds.grayAlpha.100" },
      _focusVisible: { boxShadow: "focusRing" },
    },
    mobileGroups: {
      display: "flex",
      flexDirection: "column",
      gap: "24px",
      padding: "16px 12px",
    },
    mobileGroupLabel: {
      marginBottom: "8px",
      fontSize: "14px",
      lineHeight: "20px",
      fontWeight: 500,
      color: "ds.gray.900",
    },
    mobileSubLink: {
      display: "flex",
      alignItems: "center",
      minHeight: "40px",
      fontSize: "16px",
      lineHeight: "24px",
      color: "ds.gray.1000",
      textDecoration: "none",
    },
    mobileActions: {
      display: "flex",
      flexDirection: "column",
      gap: "16px",
      marginTop: "32px",
      paddingBottom: "24px",
    },
  },
  variants: {
    scrolled: {
      true: {
        root: {
          backgroundColor: "ds.background.200",
          boxShadow: "0 1px 0 0 {colors.ds.grayAlpha.400}",
        },
      },
    },
    navOpen: {
      true: { root: { backgroundColor: "ds.background.200", boxShadow: "none" } },
    },
    mobileOpen: {
      true: {
        root: {
          [NAV_COLLAPSE]: { backgroundColor: "ds.background.100", boxShadow: "none" },
        },
        mobilePanel: { [NAV_COLLAPSE]: { display: "block" } },
      },
    },
  },
});
